backup-org-git: Check required executables at start

diff --git a/scripts/backup-org-git b/scripts/backup-org-git
--- a/scripts/backup-org-git
+++ b/scripts/backup-org-git
@@ -5,19 +5,22 @@ set -e
 # Git branch on which a new commit is added
 branch=master
 
-GIT_COMMAND=${GIT_COMMAND:-git}
-
 has() { command -v "$1" >/dev/null 2>/dev/null; }
 
 err() { echo "Error: $*" >&2; }
 
-if [[ ! -x ${GIT_COMMAND} ]] && ! has git; then
-    GIT_COMMAND="$HOME/.nix-profile/bin/git"
-    if [[ ! -x ${GIT_COMMAND} ]]; then
-        err "git is unavailable"
-        exit 20
+require() {
+    local prog="$1"
+    if ! has "$prog"; then
+        err "Missing a required executable $prog"
+        exit 22
     fi
-fi
+}
+
+require git
+require rm
+require cut
+require tr
 
 # Ensure that this script is run at the root of a Git repository
 if [ ! -d .git ]; then
